#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['TC_ENV'] || 'development'
connect_to database

wellcome_message = "\nWellcome to Ruby Closet!\n
  Need something to wear?\n
  - To generate an outfit to wear, type 'some code goes here'
  - To add an outfit to your closets inventory, type: ruby testcloset add 'your_piece_of_clothing'
  - To list your Ruby Closet inventory, type: ruby testcloset list
  - To remove clothing in your Ruby Closet, type: ruby testcloset remove 'your_piece_of_clothing'"
  puts wellcome_message

# ARGV = [add, foo]
command = ARGV[0]

if command == "add"
  clothing_name = ARGV[1]
  clothes = Clothing.new(name: clothing_name)
  if clothes.save
    puts "Success!"
  else
    puts "Failure :( #{clothes.errors.full_messages.join(", ")}"
  end
elsif command == "list"
  clothings = Clothing.all
  clothings.each_with_index do |clothes, i|
    puts "#{i+1}. #{clothes.name}"
  end
elsif command == "remove"
  clothing_name = ARGV[1]
  matching_clothes = Clothing.where(name: clothing_name).all
  matching_clothes.each do |clothes|
    clothes.destroy
  end
end