#!/usr/bin/env ruby

require_relative 'bootstrap_ar'
database = ENV['FP_ENV'] || 'development'
connect_to database

# ARGV = [add, foo]
command = ARGV[0]

if command == "add"
  clothing_name = ARGV[1]
  clothes = Clothing.new(name: clothing_name)
  if clothes.save
    puts "Success!"
  else
    puts "Failure :( #{clothes.errors.full_messages.join(", ")}"
  end
elsif command == "list"
  clothings = Clothing.all
  clothings.each_with_index do |clothes, i|
    puts "#{i+1}. #{clothes.name}"
  end
elsif command == "remove"
  clothing_name = ARGV[1]
  matching_clothes = Clothing.where(name: clothing_name).all
  matching_clothes.each do |clothes|
    clothes.destroy
  end
end









# require_relative 'bootstrap_ar'
# database = ENV['TC_ENV'] || 'development'
# connect_to database

# # ARGV = [add, Dress]
# command = ARGV[0]  

# if command == "add"
#   clothes_name = ARGV[1]
#   clothing = Clothing.new(name: clothes_name)
#   if clothing.save
#     puts "Success!"
#   else 
#     puts "Failure :( #{clothing.errors.full_messages.join(", ")}"
#   end
# elsif command == "list"
#   clothes = Clothing.all
#   clothes.each_with_index do |clothing, i|
#     puts "#{i+1}. #{clothing.name}"
#   end
# elsif command == "remove"
#   clothes_name = ARGV[1]
#   matching_clothes = Clothing.where(name: clothes_name).all
#   matching_clothes.each do |clothing|
#     clothing.destroy
#   end
# end


